services:
  engine_local:
    image: 'optionedge/engine:1.0.39'
    container_name: engine_local
    restart: always
    ports:
     - "7500:8080"
    environment:
     - TZ=Asia/Kolkata
     - Auth:Domain=https://auth.optionedge.in/oidc
     - Auth:Audience=https://api.optionedge.in
     - ASPNETCORE_ENVIRONMENT=Production
     - RuntimeSettings__ProfileApiBaseUrl=https://api.optionedge.in/
     - RuntimeSettings__MessageQueueConnectionString=host=rabbitmq_local:5672;virtualhost=/;username=guest;password=guest;persistentMessages=false
     - RuntimeSettings__DataFolder=/app/data
    depends_on:
      - rabbitmq_local
    volumes:
      - ./data:/app/data
    networks:
        - optionedge_local
  
  rabbitmq_local:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq_local
    restart: always
    volumes:
        - ./.queue/queue/data/:/var/lib/rabbitmq/
        - ./.queue/queue/log/:/var/log/rabbitmq
    networks:
        - optionedge_local

networks:
  optionedge_local:
